groups:
  - name: example-rule-group
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{image!="",container_name!=""}[5m])) by (namespace) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected in {{ $labels.namespace }}"
          description: "CPU usage is above 90% for more than 5 minutes in namespace {{ $labels.namespace }}."

      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{image!=""}) by (namespace) / sum(container_spec_memory_limit_bytes{image!=""}) by (namespace) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage detected in {{ $labels.namespace }}"
          description: "Memory usage is above 80% for more than 5 minutes in namespace {{ $labels.namespace }}."

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status!~"2.."}[5m])) by (service) / sum(rate(http_requests_total[5m])) by (service) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected for service {{ $labels.service }}"
          description: "Error rate is above 10% for more than 5 minutes for service {{ $labels.service }}."
